### ISSUE TITLE
Unable to add  Flurry.Analytics.ios project reference to unified API project in Xamarin.iOS.

### ISSUE THREAD

**Issue by Harikrishnav21** [mattleibow/Flurry.Analytics#15]
After adding reference I am getting below errors.
MTOUCH: Error MT5212: Native linking failed, duplicate symbol: '_llvm.cmdline'. (MT5212) 
and
MTOUCH: Error MT5213: Duplicate symbol in: 
/obj/iPhone/Debug/mtouch-cache/libFlurry_7.2.1.a(PLCrashReportMachineInfo.o) (Location related to previous error) (MT5213)

**Comment by mojjeietuna** [comment]
Update XCode
