### ISSUE TITLE
iOS 64 bit

### ISSUE THREAD

**Issue by Zambiorix** [mattleibow/Flurry.Analytics#3]
Hi,

Great work, love your component!

I wonder, will you include a version that targets the new unified Xamarin,iOS (32/64 bit) framework?

Now it's only working for the classic 32 bit framework. Apple is forcing 64 bit from feb/15 on.

Thanks!
Gerd

**Comment by andrem0** [comment]
Hello. I am also wondering if you will add support for this?

**Comment by mattleibow** [comment]
Hi,
Support for iOS Unified was added some versions back. Support for iOS Classic and Windows Phone 7 has been dropped in this release. This can be added back if there are requirements.
