### ISSUE TITLE
Error on compiling armv7s + ARM64

### ISSUE THREAD

**Issue by luigisaggese** [mattleibow/Flurry.Analytics#6]
.../MTOUCH: Error MT5309: Native linking error: file is universal (5 slices) but does not contain a(n) armv7s slice: .../mtouch-cache/libFlurry_6.0.0.a file '.../mtouch-cache/libFlurry_6.0.0.a' for architecture armv7s (MT5309)

**Comment by mattleibow** [comment]
Hi @luigisaggese, unfortunately, Flurry does not support the armv7s architecture. If this platform is needed, you may have to contact them. However, this architecture is not really necessary as I think these devices can also run 64-bit apps... but I may be wrong here.
