### ISSUE TITLE
how about Flurry Publisher AD network SDK?

### ISSUE THREAD

**Issue by kenchan97** [mattleibow/Flurry.Analytics#9]
i have try to add flurry ad network to xamarin.
and it have not error showed when xamarin compile the jar file.

but it is not working when i try to test it.
for eg: no FlurryAdInterstitial class was mapped.

and api.xml show this:
class abstract="false" deprecated="not deprecated" extends="java.lang.Object" extends-generic-aware="java.lang.Object" final="false" name="FlurryAdInterstitial.2" static="true" visibility=""

it is strange , name = FlurryAdInterstitial.2 , 
so i try to rename this by meta.xml but no luck.
can you help me ?

**Comment by mattleibow** [comment]
@kenchan97 I know it has been some time, but I added the ad SDK a few months back. If you are still looking at this, you can try that. And you can see my code as well for comparison.
